extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018 # TODO: Atualizar para 2022 assim que atualizar o TS
  sourceType: module
plugins: []
env:
  browser: true
  es6: true # TODO: Atualizar key para es2022 assim que atualizar o TS
settings:
  react:
    version: detect
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
    node:
      extensions:
        - .ts
        - .tsx
      moduleDirectory:
        - src
        - node_modules
rules:
  import/no-unresolved:
    - 2
    - ignore:
        - '.svg$'
        - '.img$'
        - '.png$'
  no-use-before-define: warn
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/explicit-module-boundary-types': off
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-trailing-spaces: error
  space-infix-ops: error
  no-unused-vars:
    - error
    - args: none
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: false
      objectsInObjects: false
  array-bracket-spacing:
    - error
    - never
  arrow-spacing:
    - error
    - before: true
      after: true
  block-spacing:
    - error
    - always
  computed-property-spacing:
    - error
    - never
  comma-spacing:
    - error
    - before: false
      after: true
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides:
        case:
          after: true

  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  no-console: error
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  eol-last:
    - error
    - always
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  array-callback-return:
    - error
    - allowImplicit: true
  consistent-return: error
  no-return-await: error
  no-useless-return: error
  react/hook-use-state: error
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.tsx'
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
      unnamedComponents: function-expression
